### ISSUE TITLE
[Documentation] README is missing information on building

### ISSUE THREAD

**Issue by Whovian9369** [Puxtril/Warframe-Exporter#12]
So I accidentally hit CTRL+ENTER before actually typing the issue, sorry!

The actual issue:
It would be nice to have [some more info in the "Building" Section](https://github.com/Puxtril/Warframe-Exporter/blob/master/README.md#building) that building on Linux can be done by:
- Downloading Unreal Engine from [the official Linux page](https://www.unrealengine.com/en-US/linux) (though logging in is required)
- Extracting the zip's `Engine/Source/Runtime/OodleDataCompression/Sdks/2.9.5/lib/` to `./bin/`.

Example file list of `./bin/` for my successful build:
```
$ ls -1N bin/
Android
IOS
Linux
LinuxArm64
Mac
TVOS
Win32
Win64
```

**Comment by Puxtril** [comment]
Apologies for the delayed response. I meant to follow-up after you edited the comment, but I didn't add it to my to-do list, so naturally I completely forgot 😬

I've just updated the build instructions in c3dafbe

**Comment by Whovian9369** [comment]
Thank you so much!
