### ISSUE TITLE
Looking for Language.bin export to .txt or .json

### ISSUE THREAD

**Issue by Kamikaze2035** [Puxtril/Warframe-Exporter#14]
We can get all the in-game text.

**Comment by Protinon** [comment]
I believe the Language.bin is packaged within the Misc package, and currently LotusLib doesn't support nested packages (though, that can be easily added).

I also believe that package is encrypted. I haven't investigated myself, do you have experience with this?

**Comment by Puxtril** [comment]
I believe the Language.bin package is encrypted. But I haven't investigated this, have you? 

I also have concerns about datamining. I can't stop people from forking this repo and making something, but adding data mining capability to an open-source project may get this shut down by DE.

**Comment by Kamikaze2035** [comment]
Duviri leaked last year, some text was from Language.bin, so I think it can be decrypted some way.

**Comment by empdarkness** [comment]
Not sure if its of any help. In another project, this was posted in relation to this and got deleted like a minute later, so take it as you will.
Uncompressed data > LZW/Huffman compression > base64 encoding > compressed data

**Comment by Puxtril** [comment]
After extracting the bin from the cache files (via Oodle decompression), I'm not seeing additional LZ compression nor base64 encoding. The text does seem readable, which may indicate it's already decompressed/decoded and just needs to be parsed, or it's still LZ compressed and needs a tiny bit of parsing to make it compatible with decompression algorithms.

**Comment by Kamikaze2035** [comment]
Glad to know this, but for safety, I hope you can delete this issue to prevent DE from changing the encryption method in the future.

**Comment by Puxtril** [comment]
You don't need to worry, the posted algorithm doesn't seem to work. And anyway, DE wouldn't change their storage format just because it was publically posted. They're more likely to change the format if someone leaks datamined information. 

Anyway, I'm not interested in investigating the Languages.bin format. But anyone is free to research and/or submit a pull request.
