### ISSUE TITLE
Running via Windows Subsystem for Linux throws "Run from terminal" dialog

### ISSUE THREAD

**Issue by Whovian9369** [Puxtril/Warframe-Exporter#21]
v2.5.1 errors with `This is a console program. It needs to be executed inside a terminal (like Powershell).` despite being run via WSL. Example screenshot is below.
![image](https://github.com/Puxtril/Warframe-Exporter/assets/5240754/7385b5d9-c4d3-4057-8bd3-f87f184e09b8)

**Comment by Puxtril** [comment]
Removed this warning, since the existence of the UI should make this error redundant. b0eb27e7f009a41bff735c65f829f147841b97b5
