### ISSUE TITLE
New texture compression formats

### ISSUE THREAD

**Issue by Puxtril** [Puxtril/Warframe-Exporter#28]
Lightmap also has textures, which has not been known to contain useful textures until recently. I've discovered 2 new compression formats alongside the usual BC1-7 and 1 uncompressed format.

12   /Lotus/Levels/CorpusGasCityRemaster/GasExit01/LevelCapture_mm.png
30   /Lotus/Levels/ClanDojo/ClanDojoDuviriDeadEnd/Landscape0/T0u0.lchm

**Comment by PrVfRu** [comment]
1999MagFaceMasksArray in Lotus\Characters\Tenno\Mag\1999Mag\Face\Texture is Array texture with 3 textures (1024px x 1024px)
HeadPoresDetailArray in Lotus\Characters\Tenno\Operator\Heads\SharedTextures is Array texture with 5 textures (512px x 512px)

**Comment by Puxtril** [comment]
Added all new formats with final commit 5ef08129933a05f386df14b038cfd31031a03b13
