### ISSUE TITLE
Material override in levels broke

### ISSUE THREAD

**Issue by PrVfRu** [Puxtril/Warframe-Exporter#29]
Level files has override function where material of original mesh can be switched with another one. This behaviour is broken for several extractor updates

![Capture (1)](https://github.com/Puxtril/Warframe-Exporter/assets/4870217/cef19580-7b20-4aa9-b758-a3a0cbb1ce68)
![Capture (2)](https://github.com/Puxtril/Warframe-Exporter/assets/4870217/31724c8a-c463-4c90-baed-5c97c2071d2a)

**Comment by Puxtril** [comment]
Fixed in 77908c795966cfecdb12e4d1f0dac28781031275
