### ISSUE TITLE
Directly typing an eport path in the ui results in an error.

### ISSUE THREAD

**Issue by Kptweedy** [Puxtril/Warframe-Exporter#33]
For example, I want to use this path export path but it results in an error because the directory has not been created
![image](https://github.com/Puxtril/Warframe-Exporter/assets/50673240/ddb5072d-f8d6-4b50-8195-9595b86ba9a2)
Compared to doing this in the CLI version where it will create a directory for you.

**Comment by Puxtril** [comment]
Fixed in 00a04c0e61bede458a20ae8d8a0742d9b56338f8

Message box now shows an option to create the folder (then continue with loading).
