### ISSUE TITLE
CLI is interactive when it shouldn't be

### ISSUE THREAD

**Issue by Sainan** [Puxtril/Warframe-Exporter#35]
When trying to export all files, the CLI requests confirmation, even when explicitly setting `--internal-path /`. Either this should be respected or some extra option could be added for a non-interactive CLI.

**Comment by Puxtril** [comment]
Yea, the CLI should be non-interactive if `internal-path` is explicitly specified. I'll make this change in the next day or so.

**Comment by Puxtril** [comment]
Fixed in 12c57eff5f3235ceaa4126065b3b698621404540
