### ISSUE TITLE
[Bug] Crash when trying to extract specific directory

### ISSUE THREAD

**Issue by Whovian9369** [Puxtril/Warframe-Exporter#38]
Trying to extract `/EE/Editor/Darkitect/Materials/PBRCompliance/Shaders/` crashes the GUI version of the tool. 

Specific file that it appears to be crashing on is `/EE/Editor/Darkitect/Materials/PBRCompliance/Shaders/PBRComplianceArchitectural/2_p.hlsl`, but can't confirm.

What I expected was for the files to be extracted or for an error to appear, but instead the whole tool crashes and closes.

**Comment by Puxtril** [comment]
Can confirm extracting shaders from `
/EE/Editor/Darkitect/Materials/PBRCompliance/Shaders/` causes a segfault. Currently finishing up another feature, but ill look at this issue after.

**Comment by Puxtril** [comment]
This was due to hard-coding "ShaderPermutationDx11" in the shader extractor. I've made package loading more dynamic, which fixed the issue:  f8a7b1d46733051c1804c30acc86f18bc28e2511
