### ISSUE TITLE
missing files on list

### ISSUE THREAD

**Issue by NekoSuneVR** [Puxtril/Warframe-Exporter#41]
not sure if is just GUI issue or game self, but Octavia Skins not listed Cache Files or anything do with octavia assets.

there be more missing items too but not sure if is app issue or game issue.

so I need some help on this to confirm it.

**Comment by Puxtril** [comment]
Most Warframe assets are located in `/Lotus/Characters/Tenno`. They also have codenames so it's not exactly straightforward. Octavia's internal name is `Bard`, which does exist for me.

A full list of internal names is documented here (not managed my me): https://kptweedy.github.io/Tutorials/wf-guides/extractor/internal-paths/

**Comment by NekoSuneVR** [comment]
what about skins, are they there too. coz on site says in /lotus/upgrades/ etc but folder doesn't esist there.

**Comment by Puxtril** [comment]
Yes skins should also be there, are you looking for one in particular that doesn't exist?

Also, where are you getting `/Lotus/Upgrades` from? Assets are not typically stored there, just metadata (which the extractor isn't built for).

**Comment by NekoSuneVR** [comment]
finding that info in here as endpoints https://omni.wf/#q=Octavia%20Diva

**Comment by NekoSuneVR** [comment]
but other that i found them

**Comment by Puxtril** [comment]
Yea most everything warframe-related is gonna be in `/Lotus/Characters/Tenno`. Armor is in `/Lotus/Characters/Tenno/Accessory`. I wouldn't rely on omni.wf to reliably point to asset locations.
